import pytest
from pathlib import Path
from gxfacebook.cookies import (
    get_cookie_file,
    get_httpx_cookies,
    has_valid_cookies,
    parse_netscape_cookies,
)
from gxfacebook.gallery import (
    clean_image_url,
    extract_all_images,
    is_valid_gallery_image,
    render_multi_image_embed,
    render_multi_image_tags,
)

SAMPLE_NETSCAPE_COOKIES = """# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

.facebook.com\tTRUE\t/\tTRUE\t1799999999\tc_user\t100088888888
#HttpOnly_.facebook.com\tTRUE\t/\tTRUE\t1799999999\txs\t24%3Aabc%3A2%3A12345
.facebook.com\tTRUE\t/\tTRUE\t1799999999\tdatr\trandomdatrtoken123
.facebook.com\tTRUE\t/\tTRUE\t1799999999\tempty_token\t
# Comment line to ignore
"""


def test_parse_netscape_cookies():
    cookies = parse_netscape_cookies(SAMPLE_NETSCAPE_COOKIES)
    assert cookies["c_user"] == "100088888888"
    assert cookies["xs"] == "24%3Aabc%3A2%3A12345"
    assert cookies["datr"] == "randomdatrtoken123"
    assert cookies["empty_token"] == ""
    assert "Comment" not in cookies


def test_cookie_file_helpers(tmp_path: Path):
    # Non-existent file
    non_existent = tmp_path / "does_not_exist.txt"
    assert get_cookie_file(non_existent) is None
    assert get_httpx_cookies(non_existent) == {}
    assert not has_valid_cookies(non_existent)

    # Empty file
    empty_cookie = tmp_path / "empty_cookies.txt"
    empty_cookie.write_text("")
    assert get_cookie_file(empty_cookie) is None
    assert get_httpx_cookies(empty_cookie) == {}
    assert not has_valid_cookies(empty_cookie)

    # Valid cookie file
    valid_cookie = tmp_path / "cookies.txt"
    valid_cookie.write_text(SAMPLE_NETSCAPE_COOKIES)
    assert get_cookie_file(valid_cookie) == str(valid_cookie)

    parsed = get_httpx_cookies(valid_cookie)
    assert parsed["c_user"] == "100088888888"
    assert parsed["xs"] == "24%3Aabc%3A2%3A12345"
    assert has_valid_cookies(valid_cookie) is True


def test_cookie_file_discovery_without_args(tmp_path: Path, monkeypatch):
    dummy_dir = tmp_path / "app"
    dummy_dir.mkdir()
    cookie_file = dummy_dir / "facebook_cookies.txt"
    cookie_file.write_text(SAMPLE_NETSCAPE_COOKIES)

    monkeypatch.setattr("gxfacebook.cookies.PROJECT_DIR", dummy_dir)
    monkeypatch.setattr(Path, "cwd", lambda: dummy_dir)

    found = get_cookie_file()
    assert found is not None
    assert "facebook_cookies.txt" in found



def test_clean_image_url():
    # JSON escaped slashes and unicode ampersands
    raw = r"https:\/\/scontent-ord5-2.xx.fbcdn.net\/v\/t39.30808-6\/photo.jpg?token=1\u0026id=2"
    cleaned = clean_image_url(raw)
    assert cleaned == "https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo.jpg?token=1&id=2"

    # Literal \\u0026 and HTML entity &amp;
    raw2 = r"https://scontent-ord5-2.xx.fbcdn.net/v/photo.jpg?a=1\\u0026b=2&amp;c=3"
    cleaned2 = clean_image_url(raw2)
    assert cleaned2 == "https://scontent-ord5-2.xx.fbcdn.net/v/photo.jpg?a=1&b=2&c=3"

    # Trailing quotes and syntax delimiters
    raw3 = 'https://scontent-ord5-2.xx.fbcdn.net/v/photo.jpg?a=1",)'
    assert clean_image_url(raw3) == "https://scontent-ord5-2.xx.fbcdn.net/v/photo.jpg?a=1"


def test_is_valid_gallery_image():
    valid = "https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/825281601_10165240020421460_n.jpg?token=1"
    assert is_valid_gallery_image(valid) is True

    # Lookaside rejection
    assert not is_valid_gallery_image("https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=123")

    # Non-fbcdn domain rejection
    assert not is_valid_gallery_image("https://example.com/photo.jpg")

    # Favicon / icon rejection
    assert not is_valid_gallery_image("https://static.xx.fbcdn.net/rsrc.php/y1/r/ay1hV6OlegS.ico")
    assert not is_valid_gallery_image("https://scontent-ord5-2.xx.fbcdn.net/v/favicon.png")
    assert not is_valid_gallery_image("https://scontent-ord5-2.xx.fbcdn.net/rsrc.php/icon.png")

    # Profile avatar & small dimensions rejection
    assert not is_valid_gallery_image("https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-1/cp0/avatar.jpg")
    assert not is_valid_gallery_image("https://scontent-ord5-2.xx.fbcdn.net/v/t1.18169-1/p50x50/photo.jpg")
    assert not is_valid_gallery_image("https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo_s.jpg")
    assert not is_valid_gallery_image("https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo_q.jpg")
    assert not is_valid_gallery_image("https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo.jpg?stp=32x32")


def test_extract_all_images_multi_image_html():
    html_sample = """<!DOCTYPE html>
    <html>
    <head>
        <meta property="og:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo1_1001_n.jpg?stp=dst-jpg_tt6&amp;token=abc" />
        <meta name="twitter:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo1_1001_n.jpg?stp=dst-jpg_tt6&amp;token=abc" />
    </head>
    <body>
        <!-- Static icons and avatars that should be ignored -->
        <img src="https://static.xx.fbcdn.net/rsrc.php/y1/r/ay1hV6OlegS.ico" />
        <img src="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-1/avatar_50x50.jpg" />
        <img src="https://lookaside.fbsbx.com/lookaside/crawler/media/?media_id=999" />

        <!-- Second and third photos in DOM -->
        <img src="https://scontent-ord5-1.xx.fbcdn.net/v/t39.30808-6/photo2_1002_n.jpg?token=def" />
        <img src="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo3_1003_n.jpg?token=ghi" />

        <!-- Fourth photo embedded in JSON script with escaped slashes -->
        <script>
            const data = {
                "images": [
                    {"uri": "https:\\/\\/scontent-ord5-1.xx.fbcdn.net\\/v\\/t39.30808-6\\/photo4_1004_n.jpg?stp=dst-jpg\\u0026token=jkl"},
                    {"uri": "https:\\/\\/scontent-ord5-2.xx.fbcdn.net\\/v\\/t39.30808-6\\/photo5_1005_n.jpg?token=mno"}
                ]
            };
        </script>
    </body>
    </html>"""

    images = extract_all_images(html_sample, max_images=4)
    # Should extract up to 4 unique photos
    assert len(images) == 4

    # Verify each image URL is clean
    for img in images:
        assert "scontent" in img
        assert "lookaside" not in img
        assert "\\/" not in img
        assert "\\u0026" not in img
        assert "&amp;" not in img

    # Check deduplication and ordering
    assert "photo1_1001_n.jpg" in images[0]
    assert "photo2_1002_n.jpg" in images[1]
    assert "photo3_1003_n.jpg" in images[2]
    assert "photo4_1004_n.jpg" in images[3]

    # Test max_images constraint
    images_limit_2 = extract_all_images(html_sample, max_images=2)
    assert len(images_limit_2) == 2


def test_extract_all_images_on_post_fixture():
    # Representative HTML snippet from Facebook post share/p/19d6PRtbEt/
    html_post = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta property="og:image:alt" content="LRT stations in Edmonton, AB" />
        <meta property="og:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/825281601_10165240020421460_2803127029525436672_n.jpg?stp=dst-jpg_tt6&amp;cstp=mx900x675&amp;ctp=p600x600&amp;_nc_cat=102&amp;ccb=1-7&amp;_nc_sid=603a64&amp;oh=00_AQMYz&amp;oe=6ABFE064" />
        <link rel="icon" href="https://static.xx.fbcdn.net/rsrc.php/y1/r/ay1hV6OlegS.ico" />
    </head>
    <body>
        <div class="content">LRT stations in Edmonton</div>
    </body>
    </html>
    """
    images = extract_all_images(html_post)
    assert len(images) == 1
    assert "825281601_10165240020421460_2803127029525436672_n.jpg" in images[0]
    assert "&amp;" not in images[0]
    assert "ay1hV6OlegS.ico" not in images


def test_render_multi_image_tags():
    imgs = [
        "https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo1.jpg?a=1&b=2",
        "https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo2.jpg?a=3&b=4",
        "https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo3.jpg?a=5&b=6",
    ]
    tags = render_multi_image_tags(imgs)

    # Twitter card tags
    assert '<meta name="twitter:card" content="summary_large_image"/>' in tags
    assert '<meta name="twitter:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo1.jpg?a=1&amp;b=2"/>' in tags

    # Multiple og:image tags for Discord 2x2 collage
    assert '<meta property="og:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo1.jpg?a=1&amp;b=2"/>' in tags
    assert '<meta property="og:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo2.jpg?a=3&amp;b=4"/>' in tags
    assert '<meta property="og:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/t39.30808-6/photo3.jpg?a=5&amp;b=6"/>' in tags


def test_render_multi_image_tags_empty():
    tags = render_multi_image_tags([])
    assert '<meta name="twitter:card" content="summary_large_image"/>' in tags
    assert "og:image" not in tags


def test_render_multi_image_embed():
    imgs = [
        "https://scontent-ord5-2.xx.fbcdn.net/v/photo1.jpg",
        "https://scontent-ord5-2.xx.fbcdn.net/v/photo2.jpg",
    ]
    html_out = render_multi_image_embed(
        "share/p/19d6PRtbEt",
        imgs,
        title="LRT Stations",
        description="Check out these stations",
    )
    assert '<meta property="og:url" content="https://www.facebook.com/share/p/19d6PRtbEt"/>' in html_out
    assert '<meta property="og:title" content="LRT Stations"/>' in html_out
    assert '<meta property="og:description" content="Check out these stations"/>' in html_out
    assert '<meta property="og:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/photo1.jpg"/>' in html_out
    assert '<meta property="og:image" content="https://scontent-ord5-2.xx.fbcdn.net/v/photo2.jpg"/>' in html_out
    assert '<meta name="twitter:card" content="summary_large_image"/>' in html_out
    assert "https://www.facebook.com/share/p/19d6PRtbEt" in html_out
